-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.companies
(
    company_id bigserial NOT NULL,
    uen text COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    industry_norm text COLLATE pg_catalog."default",
    employees_est integer,
    revenue_bucket text COLLATE pg_catalog."default",
    incorporation_year integer,
    sg_registered boolean DEFAULT true,
    last_seen timestamp with time zone DEFAULT now(),
    website_domain text COLLATE pg_catalog."default",
    industry_code text COLLATE pg_catalog."default",
    company_size integer,
    annual_revenue text COLLATE pg_catalog."default",
    hq_city text COLLATE pg_catalog."default",
    hq_country text COLLATE pg_catalog."default",
    linkedin_url text COLLATE pg_catalog."default",
    founded_year integer,
    tech_stack text[] COLLATE pg_catalog."default",
    ownership_type text COLLATE pg_catalog."default",
    funding_status jsonb,
    employee_turnover double precision,
    web_traffic bigint,
    email text COLLATE pg_catalog."default",
    phone_number text COLLATE pg_catalog."default",
    location_city text COLLATE pg_catalog."default",
    location_country text COLLATE pg_catalog."default",
    CONSTRAINT companies_pkey PRIMARY KEY (company_id),
    CONSTRAINT companies_uen_key UNIQUE (uen)
);

CREATE TABLE IF NOT EXISTS public.company_enrichment_runs
(
    company_id bigint NOT NULL,
    run_id bigint NOT NULL,
    domain text COLLATE pg_catalog."default",
    about_text text COLLATE pg_catalog."default",
    tech_stack text[] COLLATE pg_catalog."default",
    jobs_count integer,
    linkedin_url text COLLATE pg_catalog."default",
    news_latest_at date,
    source_json jsonb,
    updated_at timestamp with time zone DEFAULT now(),
    degraded_reasons text COLLATE pg_catalog."default",
    CONSTRAINT company_enrichment_runs_pkey PRIMARY KEY (company_id, run_id)
);

CREATE TABLE IF NOT EXISTS public.contacts
(
    contact_id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id bigint NOT NULL,
    full_name text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    email_verified boolean DEFAULT false,
    verification_confidence double precision,
    job_title text COLLATE pg_catalog."default",
    department text COLLATE pg_catalog."default",
    linkedin_profile text COLLATE pg_catalog."default",
    phone_number text COLLATE pg_catalog."default",
    seniority text COLLATE pg_catalog."default",
    location_city text COLLATE pg_catalog."default",
    location_country text COLLATE pg_catalog."default",
    contact_source text COLLATE pg_catalog."default",
    email_engagement jsonb,
    last_interaction timestamp with time zone,
    preferred_contact_method text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT contacts_pkey PRIMARY KEY (contact_id)
);

CREATE TABLE IF NOT EXISTS public.email_verification_cache
(
    email text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default",
    confidence double precision,
    checked_at timestamp with time zone DEFAULT now(),
    CONSTRAINT email_verification_cache_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.enrichment_runs
(
    run_id bigserial NOT NULL,
    started_at timestamp with time zone DEFAULT now(),
    tenant_id integer,
    ended_at timestamp with time zone,
    status text COLLATE pg_catalog."default",
    langsmith_trace_url text COLLATE pg_catalog."default",
    degraded boolean DEFAULT false,
    CONSTRAINT enrichment_runs_pkey PRIMARY KEY (run_id)
);

ALTER TABLE IF EXISTS public.enrichment_runs
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.icp_rules
(
    rule_id serial NOT NULL,
    name text COLLATE pg_catalog."default",
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    tenant_id integer NOT NULL DEFAULT 1,
    CONSTRAINT icp_rules_pkey PRIMARY KEY (rule_id),
    CONSTRAINT icp_rules_tenant_name_key UNIQUE (tenant_id, name)
);

ALTER TABLE IF EXISTS public.icp_rules
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.lead_emails
(
    email text COLLATE pg_catalog."default" NOT NULL,
    company_id bigint,
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    role_title text COLLATE pg_catalog."default",
    verification_status text COLLATE pg_catalog."default",
    smtp_confidence numeric,
    left_company boolean DEFAULT false,
    role_last_seen date,
    source text COLLATE pg_catalog."default",
    last_verified_at timestamp with time zone,
    bounce_count integer DEFAULT 0,
    CONSTRAINT lead_emails_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.lead_features
(
    company_id integer NOT NULL,
    features jsonb,
    tenant_id integer,
    CONSTRAINT lead_features_pkey PRIMARY KEY (company_id)
);

ALTER TABLE IF EXISTS public.lead_features
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.lead_scores
(
    company_id integer NOT NULL,
    score double precision,
    bucket text COLLATE pg_catalog."default",
    rationale text COLLATE pg_catalog."default",
    cache_key text COLLATE pg_catalog."default",
    tenant_id integer,
    CONSTRAINT lead_scores_pkey PRIMARY KEY (company_id)
);

ALTER TABLE IF EXISTS public.lead_scores
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.odoo_connections
(
    tenant_id integer NOT NULL,
    base_url text COLLATE pg_catalog."default",
    db_name text COLLATE pg_catalog."default",
    auth_type text COLLATE pg_catalog."default",
    secret text COLLATE pg_catalog."default",
    active boolean DEFAULT true,
    CONSTRAINT odoo_connections_pkey PRIMARY KEY (tenant_id)
);

CREATE TABLE IF NOT EXISTS public.onboarding_status
(
    tenant_id integer NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    error text COLLATE pg_catalog."default",
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT onboarding_status_pkey PRIMARY KEY (tenant_id)
);

CREATE TABLE IF NOT EXISTS public.qa_samples
(
    run_id bigint NOT NULL,
    tenant_id integer NOT NULL,
    company_id integer NOT NULL,
    bucket character varying(16) COLLATE pg_catalog."default" NOT NULL,
    checks jsonb NOT NULL,
    result character varying(16) COLLATE pg_catalog."default" NOT NULL DEFAULT 'needs_review'::character varying,
    notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT qa_samples_pkey PRIMARY KEY (run_id, tenant_id, company_id)
);

ALTER TABLE IF EXISTS public.qa_samples
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.run_event_logs
(
    run_id bigint NOT NULL,
    tenant_id integer NOT NULL,
    stage character varying(64) COLLATE pg_catalog."default" NOT NULL,
    company_id integer,
    event character varying(64) COLLATE pg_catalog."default" NOT NULL,
    status character varying(32) COLLATE pg_catalog."default" NOT NULL,
    error_code character varying(64) COLLATE pg_catalog."default",
    duration_ms integer,
    trace_id text COLLATE pg_catalog."default",
    extra jsonb,
    ts timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE IF EXISTS public.run_event_logs
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.run_manifests
(
    run_id bigint NOT NULL,
    tenant_id integer NOT NULL,
    selected_ids bigint[] NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT run_manifests_pkey PRIMARY KEY (run_id)
);

ALTER TABLE IF EXISTS public.run_manifests
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.run_stage_stats
(
    run_id bigint NOT NULL,
    tenant_id integer NOT NULL,
    stage character varying(64) COLLATE pg_catalog."default" NOT NULL,
    count_total integer DEFAULT 0,
    count_success integer DEFAULT 0,
    count_error integer DEFAULT 0,
    p50_ms integer DEFAULT 0,
    p95_ms integer DEFAULT 0,
    p99_ms integer DEFAULT 0,
    CONSTRAINT run_stage_stats_pkey PRIMARY KEY (run_id, tenant_id, stage)
);

ALTER TABLE IF EXISTS public.run_stage_stats
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.run_summaries
(
    run_id bigint NOT NULL,
    tenant_id integer NOT NULL,
    candidates integer DEFAULT 0,
    processed integer DEFAULT 0,
    batches integer DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT run_summaries_pkey PRIMARY KEY (run_id)
);

ALTER TABLE IF EXISTS public.run_summaries
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.run_vendor_usage
(
    run_id bigint NOT NULL,
    tenant_id integer NOT NULL,
    vendor character varying(64) COLLATE pg_catalog."default" NOT NULL,
    calls integer DEFAULT 0,
    errors integer DEFAULT 0,
    tokens_input integer DEFAULT 0,
    tokens_output integer DEFAULT 0,
    cost_usd numeric(12, 4) DEFAULT 0,
    rate_limit_hits integer DEFAULT 0,
    quota_exhausted boolean DEFAULT false,
    CONSTRAINT run_vendor_usage_pkey PRIMARY KEY (run_id, tenant_id, vendor)
);

ALTER TABLE IF EXISTS public.run_vendor_usage
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.ssic_ref
(
    code text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    version text COLLATE pg_catalog."default" NOT NULL,
    effective_date date NOT NULL DEFAULT CURRENT_DATE,
    source_file_hash text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    fts tsvector,
    CONSTRAINT ssic_ref_pkey PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS public.staging_acra_companies
(
    uen text COLLATE pg_catalog."default" NOT NULL,
    issuance_agency_id text COLLATE pg_catalog."default",
    entity_name text COLLATE pg_catalog."default",
    entity_type_description text COLLATE pg_catalog."default",
    business_constitution_description text COLLATE pg_catalog."default",
    company_type_description text COLLATE pg_catalog."default",
    paf_constitution_description text COLLATE pg_catalog."default",
    entity_status_description text COLLATE pg_catalog."default",
    registration_incorporation_date text COLLATE pg_catalog."default",
    uen_issue_date text COLLATE pg_catalog."default",
    address_type text COLLATE pg_catalog."default",
    block text COLLATE pg_catalog."default",
    street_name text COLLATE pg_catalog."default",
    level_no text COLLATE pg_catalog."default",
    unit_no text COLLATE pg_catalog."default",
    building_name text COLLATE pg_catalog."default",
    postal_code text COLLATE pg_catalog."default",
    other_address_line1 text COLLATE pg_catalog."default",
    other_address_line2 text COLLATE pg_catalog."default",
    account_due_date text COLLATE pg_catalog."default",
    annual_return_date text COLLATE pg_catalog."default",
    primary_ssic_code integer,
    primary_ssic_description text COLLATE pg_catalog."default",
    primary_user_described_activity text COLLATE pg_catalog."default",
    secondary_ssic_code text COLLATE pg_catalog."default",
    secondary_ssic_description text COLLATE pg_catalog."default",
    secondary_user_described_activity text COLLATE pg_catalog."default",
    no_of_officers integer,
    former_entity_name1 text COLLATE pg_catalog."default",
    former_entity_name2 text COLLATE pg_catalog."default",
    former_entity_name3 text COLLATE pg_catalog."default",
    former_entity_name4 text COLLATE pg_catalog."default",
    former_entity_name5 text COLLATE pg_catalog."default",
    former_entity_name6 text COLLATE pg_catalog."default",
    former_entity_name7 text COLLATE pg_catalog."default",
    former_entity_name8 text COLLATE pg_catalog."default",
    former_entity_name9 text COLLATE pg_catalog."default",
    former_entity_name10 text COLLATE pg_catalog."default",
    former_entity_name11 text COLLATE pg_catalog."default",
    former_entity_name12 text COLLATE pg_catalog."default",
    former_entity_name13 text COLLATE pg_catalog."default",
    former_entity_name14 text COLLATE pg_catalog."default",
    former_entity_name15 text COLLATE pg_catalog."default",
    uen_of_audit_firm1 text COLLATE pg_catalog."default",
    name_of_audit_firm1 text COLLATE pg_catalog."default",
    uen_of_audit_firm2 text COLLATE pg_catalog."default",
    name_of_audit_firm2 text COLLATE pg_catalog."default",
    uen_of_audit_firm3 text COLLATE pg_catalog."default",
    name_of_audit_firm3 text COLLATE pg_catalog."default",
    uen_of_audit_firm4 text COLLATE pg_catalog."default",
    name_of_audit_firm4 text COLLATE pg_catalog."default",
    uen_of_audit_firm5 text COLLATE pg_catalog."default",
    name_of_audit_firm5 text COLLATE pg_catalog."default",
    CONSTRAINT staging_acra_companies_pkey PRIMARY KEY (uen)
);

CREATE TABLE IF NOT EXISTS public.staging_raw_acra
(
    uen text COLLATE pg_catalog."default",
    issuance_agency_id text COLLATE pg_catalog."default",
    entity_name text COLLATE pg_catalog."default",
    entity_type_description text COLLATE pg_catalog."default",
    business_constitution_description text COLLATE pg_catalog."default",
    company_type_description text COLLATE pg_catalog."default",
    paf_constitution_description text COLLATE pg_catalog."default",
    entity_status_description text COLLATE pg_catalog."default",
    registration_incorporation_date text COLLATE pg_catalog."default",
    uen_issue_date text COLLATE pg_catalog."default",
    address_type text COLLATE pg_catalog."default",
    block text COLLATE pg_catalog."default",
    street_name text COLLATE pg_catalog."default",
    level_no text COLLATE pg_catalog."default",
    unit_no text COLLATE pg_catalog."default",
    building_name text COLLATE pg_catalog."default",
    postal_code text COLLATE pg_catalog."default",
    other_address_line1 text COLLATE pg_catalog."default",
    other_address_line2 text COLLATE pg_catalog."default",
    account_due_date text COLLATE pg_catalog."default",
    annual_return_date text COLLATE pg_catalog."default",
    primary_ssic_code text COLLATE pg_catalog."default",
    primary_ssic_description text COLLATE pg_catalog."default",
    primary_user_described_activity text COLLATE pg_catalog."default",
    secondary_ssic_code text COLLATE pg_catalog."default",
    secondary_ssic_description text COLLATE pg_catalog."default",
    secondary_user_described_activity text COLLATE pg_catalog."default",
    no_of_officers text COLLATE pg_catalog."default",
    former_entity_name1 text COLLATE pg_catalog."default",
    former_entity_name2 text COLLATE pg_catalog."default",
    former_entity_name3 text COLLATE pg_catalog."default",
    former_entity_name4 text COLLATE pg_catalog."default",
    former_entity_name5 text COLLATE pg_catalog."default",
    former_entity_name6 text COLLATE pg_catalog."default",
    former_entity_name7 text COLLATE pg_catalog."default",
    former_entity_name8 text COLLATE pg_catalog."default",
    former_entity_name9 text COLLATE pg_catalog."default",
    former_entity_name10 text COLLATE pg_catalog."default",
    former_entity_name11 text COLLATE pg_catalog."default",
    former_entity_name12 text COLLATE pg_catalog."default",
    former_entity_name13 text COLLATE pg_catalog."default",
    former_entity_name14 text COLLATE pg_catalog."default",
    former_entity_name15 text COLLATE pg_catalog."default",
    uen_of_audit_firm1 text COLLATE pg_catalog."default",
    name_of_audit_firm1 text COLLATE pg_catalog."default",
    uen_of_audit_firm2 text COLLATE pg_catalog."default",
    name_of_audit_firm2 text COLLATE pg_catalog."default",
    uen_of_audit_firm3 text COLLATE pg_catalog."default",
    name_of_audit_firm3 text COLLATE pg_catalog."default",
    uen_of_audit_firm4 text COLLATE pg_catalog."default",
    name_of_audit_firm4 text COLLATE pg_catalog."default",
    uen_of_audit_firm5 text COLLATE pg_catalog."default",
    name_of_audit_firm5 text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.summaries
(
    id bigserial NOT NULL,
    company_id bigint,
    url text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    content_summary text COLLATE pg_catalog."default",
    key_pages jsonb,
    signals jsonb,
    rule_score integer,
    rule_band text COLLATE pg_catalog."default",
    shortlist jsonb,
    crawl_metadata jsonb,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT summaries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tenant_users
(
    tenant_id integer NOT NULL,
    user_id text COLLATE pg_catalog."default" NOT NULL,
    roles text[] COLLATE pg_catalog."default",
    CONSTRAINT tenant_users_pkey PRIMARY KEY (tenant_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.tenants
(
    tenant_id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" DEFAULT 'active'::text,
    CONSTRAINT tenants_pkey PRIMARY KEY (tenant_id)
);

ALTER TABLE IF EXISTS public.company_enrichment_runs
    ADD CONSTRAINT company_enrichment_runs_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES public.companies (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.company_enrichment_runs
    ADD CONSTRAINT company_enrichment_runs_run_id_fkey FOREIGN KEY (run_id)
    REFERENCES public.enrichment_runs (run_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.contacts
    ADD CONSTRAINT contacts_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES public.companies (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.icp_rules
    ADD CONSTRAINT fk_icp_rules_tenant FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (tenant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;
CREATE INDEX IF NOT EXISTS idx_icp_rules_tenant
    ON public.icp_rules(tenant_id);


ALTER TABLE IF EXISTS public.icp_rules
    ADD CONSTRAINT icp_rules_tenant_fk FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (tenant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_icp_rules_tenant
    ON public.icp_rules(tenant_id);


ALTER TABLE IF EXISTS public.lead_emails
    ADD CONSTRAINT lead_emails_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES public.companies (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.odoo_connections
    ADD CONSTRAINT odoo_connections_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (tenant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS odoo_connections_pkey
    ON public.odoo_connections(tenant_id);


ALTER TABLE IF EXISTS public.onboarding_status
    ADD CONSTRAINT onboarding_status_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (tenant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS onboarding_status_pkey
    ON public.onboarding_status(tenant_id);


ALTER TABLE IF EXISTS public.summaries
    ADD CONSTRAINT summaries_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES public.companies (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_summaries_company
    ON public.summaries(company_id);


ALTER TABLE IF EXISTS public.tenant_users
    ADD CONSTRAINT tenant_users_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants (tenant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;